
// 豆腐块的初始化配置
export const doufuSelectList = [
  {
    label: 'B2B销售额',
    value: 'sales',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B订单量',
    value: 'orderQuantity',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B销量',
    value: 'sales1',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B销售额占比',
    value: 'salesQuantity',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B平均售价',
    value: 'avgPrice',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B平均客单价',
    value: 'pct',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: 'B2B销量/订单量',
    value: 'salesQuantityDivOrderQuantity',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
  {
    label: '占位',
    value: '占位',
    show: true,
    data: 0,
    lastData: 0,
    ratio: 0,
  },
];
